{{- if and ( .Values.monitoring.serviceMonitor.enabled ) ( .Values.monitoring.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app.fullname" . }}-prometheus-exporter
  labels:
  {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.monitoring.serviceMonitor.selector }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}

spec:
  selector:
    matchLabels:
    {{- include "app.selectorLabels" . | nindent 6 }}
    {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: {{ .Values.service.metricsPort }}
    path: /metrics
    {{- with .Values.monitoring.serviceMonitor.honorLabels }}
    honorLabels: {{ . }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.interval }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.scrapeTimeout}}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- with .Values.monitoring.serviceMonitor.scheme }}
    scheme: {{ . }}
    {{- end }}
    {{- with .Values.monitoring.serviceMonitor.tlsConfig }}
    tlsConfig:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.monitoring.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.monitoring.serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.bearerTokenSecret }}
    bearerTokenSecret:
      name: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.name }}
      key: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.key }}
      {{- if .Values.monitoring.serviceMonitor.bearerTokenSecret.optional }}
      optional: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.optional }}
      {{- end }}
    {{- end }}
  jobLabel: {{ template "app.fullname" . }}-prometheus-exporter
{{- end }}
